c = int(0)


while (c < 9999999999):
    print("Digite um número que você quer ver a tabuada")
    a = int(input())
    s1 = int(a * 0)
    s2 = int(a * 1)
    s3 = int(a * 2)
    s4 = int(a * 3)
    s5 = int(a * 4)
    s6 = int(a * 5)
    s7 = int(a * 6)
    s8 = int(a * 7)
    s9 = int(a * 8)
    s10 = int(a * 9)
    s11 = int(a * 10)
    print(f"{s1}")
    print(f"{s2}")
    print(f"{s3}")
    print(f"{s4}")
    print(f"{s5}")
    print(f"{s6}")
    print(f"{s7}")
    print(f"{s8}")
    print(f"{s9}")
    print(f"{s10}")
    print(f"{s11}")