for cont in range(0,10,1):
    print("Digite um número e veja sua tabuada")
    a = int(input())
    a2 = int(a * 0)
    print(f"{a2}")
    a3 = int(a * 1)
    print(f"{a3}")
    a4 = int(a * 2)
    print(f"{a4}")
    a5 = int(a * 3)
    print(f"{a5}")
    a6 = int(a * 4)
    print(f"{a6}")
    a7 = int(a * 5)
    print(f"{a7}")
    a8 = int(a * 6)
    print(f"{a8}")
    a9 = int(a * 7)
    print(f"{a9}")
    a10 = int(a * 8)
    print(f"{a10}")
    a11 = int(a * 9)
    print(f"{a11}")
    a12 = int(a * 10)
    print(f"{a12}")